name: all_plugins

on:
  push:
    branches: [master]
    paths-ignore:
      - "docs/**"
      - "website/**"
      - "**.md"
  pull_request:
    branches: ['**']
    paths-ignore:
      - "docs/**"
      - "website/**"
      - "**.md"
jobs:
  analyze:
    name: analyze
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'

      - name: "Install Tools"
        run: |
          ./.github/workflows/scripts/install-tools.sh
      
      - name: "Bootstrap Workspace"
        run: melos bootstrap
      
      - name: "Set env keys"
        env: 
          STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLISHABLE_KEY }}
        run: |
          ./.github/workflows/scripts/env-files.sh

      - name: "Run Analyze"
        run: melos run analyze
     
      - name: "Pub Check"
        run: |
          melos exec -c 1 --no-private --ignore="*example*"  -- \
            pub publish --dry-run

  test:
    name: test
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'

    - name: "Install Tools"
      run: |
        ./.github/workflows/scripts/install-tools.sh
    
    - name: "Bootstrap Workspace"
      run: melos bootstrap
      
    - name: "Set env keys"
      env: 
        STRIPE_PUBLISHABLE_KEY: ${{ secrets.STRIPE_PUBLISHABLE_KEY }}
        STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
      run: |
        ./.github/workflows/scripts/env-files.sh

    - name: "Run unittest"
      run: melos run unittest
      
    - name: "Start dev server"
      working-directory: example/server
      run: npm install && (npm run start:dev &) && cd ..

    - name: "Set IP address"
      working-directory: example
      run: echo "const kApiUrl='''$(ifconfig | grep 'inet ' | grep -v '127.0.0.1' | awk '{print $2}')''';" > integration_test/ip.dart

    - name: "Print ip.dart"
      working-directory: example
      run: cat integration_test/ip.dart

    - name: "Run test"
      working-directory: example
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        script: sleep 15 && flutter drive --driver test_driver/integration_test.dart --target=integration_test/app_test.dart
